# -*- coding: utf-8 -*-
"""Amazon Sales Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPfm2atA9XTQ5W6NzQOqRI1qV_tM-8uP

Welcome to Exploratory Analysis
Amazon Sales Data Questions and Answers using pandas


Suggestions are welcome for any changes in codes.
"""

'''first we import numpy pandas and matplotlib
   as we will need them to answer our business questions'''

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

'''we have the our data file uploaded @google drive, therefore we have created variable path
    to store link address of our  data set to use it for creating DataFrame'''


path = '/content/drive/MyDrive/Amazon Sales data.csv'

''' As our file is in .csv format we are creating our dataframe [df]
    using pandas .read_csv() function'''

df = pd.read_csv(path)

''' Simply printing our dataset to get familier with it'''

df

"""KPIs

"""

#1. Total number of orders
df['Order ID'].count()

#2.	Total Revenue in $
df['Total Revenue'].sum()

#3.	Total Cost in $
df['Total Cost'].sum()

#4. Total Profit $
df['Total Profit'].sum()

#5.	Average profit margin %
df['Total Profit'].sum()*100 /df['Total Revenue'].sum()

#6. Total Units Sold #
df['Units Sold'].sum()

#7.	Avg number of units per order #
df['Units Sold'].sum()/df['Order ID'].count()

"""Category Analysis [Item Type]"""

#1.	Top 5 item types by total revenue
df.groupby('Item Type').sum('Total Revenue').sort_values('Total Revenue',ascending=False).head()['Total Revenue']

#2.	Top 5 by total units sold
df.groupby('Item Type').sum('Units Sold').sort_values('Units Sold',ascending=False).head()['Units Sold']

#3.	Bottom 5 by total units sold
df.groupby('Item Type').sum('Units Sold').sort_values('Units Sold',ascending=True).head()['Units Sold']

#4.	Top 5 by average profit margin
df.groupby('Item Type').mean('Profit Margin').sort_values('Profit Margin',ascending=False).head()[['Unit Price','Profit Margin']]

#5.	Bottom 5 by average profit margin
df.groupby('Item Type').mean('Profit Margin').sort_values('Profit Margin',ascending=True).head()[['Unit Price','Profit Margin']]

"""Regional Analysis"""

#1.	Region wise total revenue
df.groupby('Region').sum('Total Revenue').sort_values('Total Revenue',ascending=False)['Total Revenue']

#2.	Region wise average profit margin
df.groupby('Region').mean('Profit Margin').sort_values('Profit Margin',ascending=False)[['Unit Price','Profit Margin']]

#3.	Region wise total units sold
df.groupby('Region').sum('Units Sold').sort_values('Units Sold',ascending=False)['Units Sold']

"""Priority Analysis"""

#1.	Priority wise total revenue
df.groupby('Order Priority').sum('Total Revenue').sort_values('Total Revenue',ascending=False)['Total Revenue']

#2.	priority wise average profit margin
df.groupby('Order Priority').mean('Profit Margin').sort_values('Profit Margin',ascending=False)[['Unit Price','Profit Margin']]

#3.	priority wise total units sold
df.groupby('Order Priority').sum('Units Sold').sort_values('Units Sold',ascending=False)['Units Sold']

"""Sales Channel Analysis"""

#1.	channel wise total revenue
df.groupby('Sales Channel').sum('Total Revenue').sort_values('Total Revenue',ascending=False)['Total Revenue']

#2.	channel wise average profit margin
df.groupby('Sales Channel').mean('Profit Margin').sort_values('Profit Margin',ascending=False)['Profit Margin']

#3.	channel wise total units sold
df.groupby('Sales Channel').sum('Units Sold').sort_values('Units Sold',ascending=False)['Units Sold']

"""Learning Note:
1. loading file from google drive.
2. read_csv
3. aggregarte
4. groupby
5. sort_values
6. selecting top/bottom 5/n head() & sort_values

"""

df.columns







